### PR TITLE
Compiler/0.12

### PR DESCRIPTION
**Pull request by AlexMouton**
Needs runSeed, which seems to have gone from QuickCheck?
LCG was separated from QC. Resolved.

### CODE REVIEW

**Comment by AlexMouton** [comment]
Hey @hdgarrood are you back in town?

**Comment by AlexMouton** [comment]
@hdgarrood psst

**Comment by AlexMouton** [comment]
@hdgarrood hey

**Comment by hdgarrood** [comment]
Hi :) can you explain the changes you made in .travis.yml please?

**Comment by AlexMouton** [comment]
Hey Harry
I hardly remember now!
I think I was very closely following the errors it was giving.
At d7aaed travis failed with
```
E: Unable to locate package g++-4.9
E: Couldn't find any package by glob 'g++-4.9'
E: Couldn't find any package by regex 'g++-4.9'
```

well if theres no such package, maybe just remove it?

**Comment by hdgarrood** [comment]
Ok. I'd usually want to go back and check why a line was added before removing it, especially if the reason why it was added was unclear. After checking the history it seems that we previously needed that particular version of g++ for the `microtime` dependency, but I suppose now the version of Ubuntu we're using must come with an appropriate C++ compiler. So that's probably fine to remove, I think.

**Comment by hdgarrood** [comment]
Can you remove those lines rather than commenting them out please?

**Comment by AlexMouton** [comment]
To me this was sufficient concern in this case, and functionality bears the
truth.
Without 4.9 travis succeeds.
Therefore 4.9 isn't necessary.
Its only a concern of this travis testing pathway, and doesn't have any
implication for any release.

A

**Comment by hdgarrood** [comment]
Thanks!

**Pull request merged**
