### PR TITLE
PureScript 0.9.1 compatibility

### PR DESCRIPTION
**Pull request by bkonkle**
Here's a nice squashed commit to merge from. Refer to #10 for code review details. Big thanks to @kika for doing most of the work! 😁

### CODE REVIEW

**Comment by hdgarrood** [comment]
Looks great. Thanks very much, both of you :)

**Comment by paulyoung** [comment]
@hdgarrood please could you make a release? :pray:

**Comment by hdgarrood** [comment]
I will once I've done some basic testing, yes.

**Comment by adarqui** [comment]
Hey hdgarrood,

I have some dependencies that are breaking as I try to migrate my code to 0.9.x. If you're not ready to make a release yet, do you have any advice on how I could work around this?

Thanks!

**Comment by hdgarrood** [comment]
@adarqui I've just tagged 4.0.0, so you could just use that now.

**Pull request merged**
