### PR TITLE
Update dependencies

### PR DESCRIPTION
**Pull request by paf31**
`free` needs this, since it has `benchotron` as a dev-dependency. You might like to release this as pre-release until 0.7.4.0 is released, since it will fail to build on 0.7.3.0 due to breaking changes in `transformers`.

The CI build will probably fail, but I've tested this locally.

### CODE REVIEW

**Comment by hdgarrood** [comment]
Thanks, I think I'll wait for 0.7.4.0. What changed in the compiler?

**Comment by paf31** [comment]
Instance resolution changed so that a particular instance in `transformers` was no longer valid.

**Comment by paf31** [comment]
This should be good to review now, and 0.7.4 is out. Thanks!

**Comment by hdgarrood** [comment]
I released this as 3.0.2.

**Pull request merged**
